name: Generate Release
run-name: Generate Release for ApoloDictionary
on:
    push:
        tags:
            -  'v*'
jobs:
    build-linux:
        uses: ./.github/workflows/generate_linux_build.yaml
        secrets: inherit
    build-windows:
        uses: ./.github/workflows/generate_windows_build.yaml
        secrets: inherit
    create-release:
        runs-on: ubuntu-latest
        needs: [build-linux, build-windows]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Create Release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ github.ref_name }}
                release_name: Release ${{ github.ref_name }}
                body_path: ./release_notes.md
                files: |
                  ./bin/artifacts/linux-x64/ApoloDictionary-linux-x64.zip
                  ./bin/artifacts/windows-x64/ApoloDictionary-windows-x64.zip
                draft: false
                prerelease: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}