name: Generate Linux Build
run-name: Generate Linux Build for ApoloDictionary
on:
    workflow_dispatch:
jobs:
    Generate-Artifcats:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v4
              with:
                    dotnet-version: '9.0.300'
            - name: Generate Linux Build x64
              run: |
                dotnet publish -c Release -r linux-x64 --self-contained true --output ./bin/artifacts/linux-x64
            - name: Upload Linux Build x64
              uses: actions/upload-artifact@v4
              with:
                    name: ApoloDictionary-linux-x64
                    path: ./bin/artifacts/linux-x64            