name: Generate Windows Build
run-name: Generate Windows Build for ApoloDictionary
on:
    workflow_call:
jobs:
    Generate-Artifcats:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v4
              with:
                    dotnet-version: '9.0.300'
            - name: Generate Windows Build x64
              run: |
                dotnet publish -c Release -r win-x64 --self-contained true --output ./bin/artifacts/win-x64
            - name: Generate Windows Build x86
              run: |
                dotnet publish -c Release -r win-x86 --self-contained true --output ./bin/artifacts/win-x86
            - name: Upload Windows Build x64
              uses: actions/upload-artifact@v4
              with:
                    name: ApoloDictionary-win-x64
                    path: ./bin/artifacts/win-x64
            - name: Upload Windows Build x86
              uses: actions/upload-artifact@v4
              with:
                    name: ApoloDictionary-win-x86
                    path: ./bin/artifacts/win-x86